#!/bin/csh
condor_submit condorjob_Georgios_ntpl_1.condor
condor_submit condorjob_Georgios_ntpl_2.condor
condor_submit condorjob_Georgios_ntpl_3.condor
condor_submit condorjob_Georgios_ntpl_4.condor
condor_submit condorjob_Georgios_ntpl_5.condor
condor_submit condorjob_Georgios_ntpl_6.condor
condor_submit condorjob_Georgios_ntpl_7.condor
condor_submit condorjob_Georgios_ntpl_8.condor
condor_submit condorjob_Georgios_ntpl_9.condor
condor_submit condorjob_Georgios_ntpl_10.condor
condor_submit condorjob_Georgios_ntpl_11.condor
condor_submit condorjob_Georgios_ntpl_12.condor
condor_submit condorjob_Georgios_ntpl_13.condor
condor_submit condorjob_Georgios_ntpl_14.condor
condor_submit condorjob_Georgios_ntpl_15.condor
condor_submit condorjob_Georgios_ntpl_16.condor
condor_submit condorjob_Georgios_ntpl_17.condor
