// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/Users/kalanand/cms/analysis/ZeeData/Fisher/./TMVAClassification.C";

#endif
